name: project_bloc
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  http: ^1.2.0
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  get_it: ^7.6.7
  oktoast: ^3.4.0
  shared_preferences: ^2.2.2
  equatable: ^2.0.5
  connectivity_plus: ^6.0.1
  change_app_package_name: ^1.1.0
  dartz: ^0.10.1
  page_transition: ^2.1.0
  meta: ^1.10.0
  qr_code_scanner: ^1.0.1
  collection: ^1.18.0
  syncfusion_flutter_charts: ^25.1.37
  pinput: ^4.0.0
  multi_select_flutter: ^4.1.3
  fluttertoast: ^8.2.8
  icons_plus: ^5.0.0
  flutter_svg: ^2.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: inter
      fonts:
        - asset: assets/fonts/inter.ttf
          weight: 400

    - family: roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/robotoblack.ttf
          weight: 400
